# -*- coding: utf-8 -*-
"""Copy of tugas kelompok 1 kel 9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I5p0au7uS43LN4UDA0V_rMOL-64kjYDe
"""

# data mentah dari soal
data_kotor = "   #001-wahyu aji-informatika-python,java,php-aktif   "

# hapus spasi depan belakang
data = data_kotor.strip()

# hapus tanda #
data = data.replace("#","")

# pisah berdasarkan -
data_split = data.split("-")

# ambil masing masing data
id_user = data_split[0]
nama = data_split[1]
jurusan = data_split[2]
skill = data_split[3]
status = data_split[4]

# olah skill
skill_list = skill.split(",")

# hitung
panjang_id = len(id_user)
jumlah_skill = len(skill_list)

# output
print(f"ID : {id_user}")
print(f"Nama : {nama}")
print(f"Jurusan : {jurusan}")
print(f"Skill : {', '.join(skill_list)}")
print(f"Status : {status}")
print(f"Panjang ID : {panjang_id}")
print(f"Jumlah Skill : {jumlah_skill}")