# -*- coding: utf-8 -*-
"""KOMPRO 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zzNAHCjSNtGaEJez6JkjWi1EcidRUDa7
"""

panjang = input('Masukkan panjang: ')
lebar = input('Masukkan lebar: ')

print('Luas =', panjang * lebar)

"""KONVERSI NUMERIK STRING"""

nama = "Wudi"
tahun_lahir = 2000

print(nama + ' lahir di tahun ' + str(tahun_lahir))