# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YcBTgElvOulDYxKIAD6mqsuIOoowLcL6
"""

nama = 'iqbal'
asal = 'índonesia'

"""string + non string"""

asal_kota = "bandar lampung"
kode_pos = 35144

asal_kota_kode_pos =asal_kotas + str(kode_pos)

asal_kota_x3 = asal_kota * 3



"""string"""

nama = 'iqbal'
asal = 'indonesi'

print(nama)

print (nama, asal)

print ("halo, nama saya",nama)

"""manipulasi string"""

print (nama, asal)