# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zzPvp6-UPWLOfxwfjn9JetoCUnreL9zH
"""

template = 'Halo, saya {nama} dari {asal}'
template_2 = 'Saya suka makan {} dan minum {}'

print(template.format(nama='Lendis Fabri', asal='Indonesia'))
# Halo, saya Lendis Fabri dari Indonesia

print(template_2.format('Nasi Goreng', 'air putih'))
# Saya suka makan Nasi Goreng dan minum air putih

nama = 'Lendis Fabri'
asal = 'Indonesia'

print(f'Perkenalkan saya {nama} dari {asal} 😎')

alamat = 'Surabaya, Jawa Timur, Indonesia'

print(alamat.split())
# ['Surabaya,', 'Jawa', 'Timur,', 'Indonesia']

print(alamat.split(','))
# ['Surabaya', ' Jawa Timur', ' Indonesia']

print(alamat.split(', '))
# ['Surabaya', 'Jawa Timur', 'Indonesia']

print('❤️'.join(['aku', 'suka', 'python']))
# aku❤️suka❤️python

print('🦕'.join(alamat.split(', ')))
# Surabaya🦕Jawa Timur🦕Indonesia

print('halo selamat pagi!'.upper())
print('Halo Selamat Siang!'.upper())

print('HALO SELAMAT PAGI!'.lower())
print('HALO SELAMAT SIANG!'.lower())

print('Indonesia Adalah Negara Asia'.swapcase())
print('AkU CINta KaMu'.swapcase())

angka = '12345'

print('Index angka 4:', angka.find('4'))
print('Index angka 45:', angka.find('45'))
print('Index angka 35:', angka.find('35'))

ibu_kota = 'Hidup Jokowi'

print(ibu_kota.replace('o', 'i'))
print(ibu_kota.replace('Jok', '🦖'))

paragraf = 'Baru-baru ini telah ditemukan sebuah meteor di suatu sungai'
x = paragraf.count('di')

print(f'Kata "di" muncul sebanyak {x} kali')